source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Redux_Example', :exclusive => true do
  pod "Redux", :path => "../"
end

target 'Redux_Tests', :exclusive => true do
  pod "Redux", :path => "../"

  
end
